<a href="https://colab.research.google.com/github/ellendulasharan/shaan/blob/main/examples_HR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n = int(input())
l = []
for i in range(n):
    k = input()
    l.append(k)
for i in l:
    if len(i) == 10 and i.isalnum():
        upper = 0
        num = 0
        for j in i:
            if j.isupper():
                upper = upper + 1
            if j in ["0","1","2","3","4","5","6","7","8",'9']:
                num = num + 1
        s = 0
        for j in range(len(i)):
            for k in range(j + 1, len(i)):
                if (i[j] == i[k]):
                    s = s + 1
        if upper>=2 and num>=3 and s == 0:
            print("Valid")
        else:
            print("Invalid")
    else:
        print("Invalid")


2
B1CD102354
B1CDEF2354
Invalid
Valid


In [ ]:
def isValid(x):
    if len(x) not in [16,19]:
        return False
    if len(x)==19:
        if x[4]!='-' or x[9]!='-' or x[14]!='-':
            return False
    if x[0] not in ['4','5','6']:
        return False
    if '-' in x:
        x=''.join(x.split('-'))
    if any(ord(x[i]) not in range(ord('0'),ord('9')+1) for i in range(16)):
        return False
    if any(str(i)*4 in x for i in range(10)):
        return False
    return True
for _ in range(int(input())):
    x=input()
    if isValid(x):
        print("Valid")
    else:
        print("Invalid")

2
2265-6699-8844-4444
Invalid
2548-6987-3658-8979
Invalid


In [ ]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
l = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k!=n]
print(l)

2
2
2
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [0, 2, 1], [0, 2, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2], [1, 2, 0], [1, 2, 1], [1, 2, 2], [2, 0, 1], [2, 0, 2], [2, 1, 0], [2, 1, 1], [2, 1, 2], [2, 2, 0], [2, 2, 1], [2, 2, 2]]


In [ ]:
n = int(input())
l = []
for i in range(n):
    s = []
    name = input()
    score = float(input())
    s.append(name)
    s.append(score)
    l.append(s)
a = []
for i in range(len(l)):
    a.append(l[i][1])
k1 = min(a)
l1 = []
for i in range(len(a)):
    if k1 != a[i]:
        l1.append(a[i])
y = min(l1)
h = []
for i in range(len(l)):
    if l[i][1] == y:
        h.append(l[i][0])
h.sort()
for i in h:
    print(i)

3
berry
22.3
harry
21.5
kerry
22.3
berry
kerry


In [ ]:
def count_substring(string, sub_string):
    c = 0
    for i in range(len(string)):
       if string[i:].startswith(sub_string):
          c = c + 1
    return c
print(count_substring('ABCDCDC','CDC'))

2


In [ ]:
thickness = int(input()) #This must me an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH


In [ ]:
s = input()
n = int(input())
l = len(s)//n
i = 0
k = l*l
while i<k:
  print(s[i:l])
  i = i+4
  l = l+4
print(s[k:])



ABCDEFGHIJKLMNOPQR
4
ABCD
EFGH
IJKL
MNOP
QR


In [ ]:
def merge_the_tools(string, k):
    l = len(string)
    f = k
    i = 0
    list1 = []
    while f <= l:
        list1.append(string[i:f])
        i += 3
        f += 3
    res = []
    for j in range(len(list1)):
        res.append(remdup(list(list1[j])))
    
    for i in range(len(res)):
        print(''.join(res[i]))

def remdup(s):
    l = []
    for i in s:
        if i not in l:
            l.append(i)
    return l
string, k = input(), int(input())
merge_the_tools(string, k)

AABCAAADA
3
AB
CA
AD


In [ ]:
def f(x):
    a=''
    for i in x:
        if i not in a:
            a=a+i
    return a
a=input()
K=int(input())
for i in range(len(a)//K):
    print(f(a[K*i:K*(i+1)]))

AABCAAADA
3
AB
CA
AD


In [ ]:
import itertools
s,k = input().split(' ')
k = int(k)
l = list(itertools.permutations(s,k))
l.sort()
for i in l:
    s = ''.join(i)
    print(s)
    

ABC 2
AB
AC
BA
BC
CA
CB


In [ ]:
import itertools

s,n = input().split(' ')
l = list(itertools.combinations(sorted(s),int(n)))
l.sort()
k = list(s)
k.sort()
for i in k:
    print(i)
for i in l:
    print(''.join(i))

ABC 2
A
B
C
AB
AC
BC


In [ ]:
from collections import Counter

n = int(input())
l1 = list(map(int,input().split(' ')))
ncus = int(input())
sizes = Counter(l1)
price = 0
for i in range(ncus):
  sz,pz = map(int,input().split())
  if sizes[sz]:
    sizes[sz] -= 1
    price += pz
print(price)


10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 20
18 100
10 5
220


In [ ]:
import cmath

n = complex(input())
print(abs(n))
print(cmath.phase(n))


2+3j
3.605551275463989
0.982793723247329


In [ ]:
import math

c, a = int(input()), int(input())

b = (c**2 + a **2)**0.5

C = math.acos((b**2 + a**2 - c**2) / (2*a*b))

print(round((180/math.pi)*C))

10
10
45


In [ ]:
from collections import defaultdict


n, m = input().split()
n = int(n)
m = int(m)
d = defaultdict(list)
for i in range(n):
    d['A'].append(input())
l = d['A']
for i in range(m):
    val = input()
    count = 1
    new_l = []
    for j in l:
        if j == val:
            new_l.append(count)
        count += 1
    if len(new_l) == 0:
        print(-1)
    else:
        print(" ".join(map(str, new_l)))b

5 2
a
b
c
a
b
a
1 4
b
2 5


In [ ]:
x = ['a','A','aA']
x.sort()
print(x)

['A', 'a', 'aA']


In [ ]:
print(2)

2


In [ ]:
import numpy as a
n,m = map(int,input().split())
l,k = [],[]
for i in range(n):
    l.append(list(map(int,input().split())))
    k.append(list(map(int,input().split())))
print('{}'.format(a.add(l,k)))
print('{}'.format(a.subtract(l,k)))
print('{}'.format(a.multiply(l,k)))
print('{}'.format(a.floor_divide(l,k)))
print('{}'.format(a.mod(l,k)))
print('{}'.format(a.power(l,k)))

2 4
1 2 3 4
1 2 3 4
5 6 7 7
5 6 7 7
[[ 2  4  6  8]
 [10 12 14 14]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [25 36 49 49]]
[[1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]]
[[     1      4     27    256]
 [  3125  46656 823543 823543]]


In [ ]:
s = input()
l = [[0,0]]
for i in range(len(s)):
    if s[i] == l[-1][1]:
        l[-1][0] += 1
    else:
        b = [0,0]
        b[1] = s[i]
        b[0] += 1
        l.append(b)    
print(l)

In [ ]:
line = input().split(' ')
rows = int(line[0])
cols = int(line[1])

table = []

for i in range(rows):
    line = input().split(' ')
    table.append([int(x) for x in line])
k = int(input())
table.sort(key = lambda x : x[k])
print(table)

5 3 
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
[[7, 1, 0], [10, 2, 5], [6, 5, 9], [9, 9, 9], [1, 23, 12]]


In [ ]:
line = input().split(' ')
rows = int(line[0])
cols = int(line[1])

table = []

for i in range(rows):
    line = input().split(' ')
    table.append([int(x) for x in line])
k = int(input())
